### ISSUE TITLE
The h5py Python package is required to save and load models

### ISSUE THREAD

**Issue by mikkelkrogsholm** [rocker-org/ml#23]
So I am having an issue. I am trying to load in a model created in python, but I simply cannot get it to work. The error tells me I need to install the `h5py` package, but no matter how I do it (or try it) I cannot get it to work. Below is the code that leads to my problem:

On mac:
First I fire up the docker image
```docker run --rm -d --name deeplearnr -p 8787 -e PASSWORD=learning_is_deep rocker/ml:3.6.0```

Then I log into it using the default `rstudio` user.

In R:
```
> system("git clone https://github.com/jleinonen/ikea-names")
Cloning into 'ikea-names'...

> library(keras)
> my_model <- load_model_hdf5("ikea-names/models/model_default.h5")
Error in load_model_hdf5("ikea-names/models/model_default.h5") : 
  The h5py Python package is required to save and load models
```

**Comment by cboettig** [comment]
Thanks for the report, we're looking into it.  appears `keras` is not finding `h5py` package installed by pip into the `virtualenv`, probably related to #20.

**Comment by cboettig** [comment]
This should be fixed now, let me know if you have further issues.  

(problem arose from `keras` not picking up the right python virtualenv, even though `reticulate` would.  by setting more env vars this issue should be fixed now).
