### ISSUE TITLE
Using rocker/ml-gpu image through Singularity on a HPC

### ISSUE THREAD

**Issue by mattwarkentin** [rocker-org/ml#25]
Hi,

First off, `Rocker` is amazing and I am very thankful for the work thats been done to support `R` in `Docker`.

I have used several of your `Docker` images in the past, but in particular I am interested in using the `rocker/ml-gpu` image on my research institutes HPC in order to go GPU-based deep learning in `R` using `tensorflow` and `keras`. 

`Singularity` provides the ability to run containers on a HPC, and supports Docker images for containerization. However, I am also aware that GPU-based Dockers require `nvidia-docker`. Do you know if the requirement for `nvidia-docker` runtime prohibits using `rocker/ml-gpu` or other GPU images through singularity on a HPC.

For context, the HPC runs CentOS 7 and Singularity 3.1.0. I am fairly new to GPU-based images and deep learning, so hopefully this question is clear.

**Comment by cboettig** [comment]
@warkentinmatt That's a great question.  I haven't tried it, but sounds like it is possible:

- https://devblogs.nvidia.com/docker-compatibility-singularity-hpc/
- https://docs.nvidia.com/ngc/ngc-user-guide/singularity.html

looks like you just use the `--nv` flag, though getting it set up for multiple gpus may be harder.  Give it a try and let us know how it goes!  I'd also definitely suggest asking your sys admins about it as they may have more detailed pointers.

**Comment by mattwarkentin** [comment]
@cboettig Thanks for the reply and sharing those links. I will definitely try it out and report back with how it goes. I will document any additional efforts made to get it going -- in case it may be helpful for others in the future.
