### ISSUE TITLE
gpg --keyserver fails because of blocked ports

### ISSUE THREAD

**Issue by restonslacker** [rocker-org/ml#3]
My employer blocks a number of outbound ports so while working on #2, I had to make another modification to the Dockerfile as follows:

```
    && gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9 \
```
becomes

```
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key E084DAB9 \
``` 

this based on the solution here: https://superuser.com/questions/64922/how-to-work-around-blocked-outbound-hkp-port-for-apt-keys#222083

I'm happy to submit a PR, but wanted to wait until #2 is resolved and wanted to see how you feel about this modification.

**Comment by eddelbuettel** [comment]
Interesting. 

In general my philosophy is influenced by the practice experienced eg in Debian, and I prefer to make as few little one-off changes as possible.  These are always well-intended but in the aggregate move the behaviour a little away from the standard which makes debugging or even comparison hard.

So I would be inclined to say no here.

(One little trick I sometimes use is to run [socat](http://www.dest-unreach.org/socat/) to 'map' or 'redirect' ports. Not sure that would help here though.)

**Comment by restonslacker** [comment]
Yes, i suspected something like this might be the case and is why i opened an issue first. Thanks for the suggestion, i'll look into other workarounds if this becomes more of an issue for me.
