### ISSUE TITLE
can we use --gpu in docker directly ie without Nvidia-docker?

### ISSUE THREAD

**Issue by stnava** [rocker-org/ml#30]
is nvidia-docker is necessary anymore. With 19.03 and older, can you do (after installing nvidia-docker-cli and nvidia-docker-toolkit) pass --gpus= parameter to docker ?

**Comment by cboettig** [comment]
Correct.  I regularly run the rocker/ml images with standard `docker run`  and the  `--gpus=` flag instead.  

(Though as you may know docker-compose no longer works with gpu option)

**Comment by stnava** [comment]
followed these steps : https://github.com/NVIDIA/nvidia-docker/issues/1243

and it worked.

thank you!

**Comment by stnava** [comment]
also needed 
```
export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
