### ISSUE TITLE
Update tensorflow-cpu to tensorflow 2.2

### ISSUE THREAD

**Issue by FvD** [rocker-org/ml#31]
The current image is still using R 3.6 and TF 1.2. it it still works for many examples but we are unable to `save_model_tf()`.

**Comment by cboettig** [comment]
Thanks for the ping, the current images are actually now over on
rocker-org/rocker-versioned2, and include:

rocker/ml
rocker/ml-verse

They have cuda10.1 (compatible with 11.1 drivers) and more recent
tensorflow etc.  feedback welcome!
